const bracketsRecursion = require('../code/balanceBrackets')

test('HEX -> RGB Works!', () => {
  expect(bracketsRecursion('')).toEqual(true)
  expect(bracketsRecursion('[]')).toEqual(true)
  expect(bracketsRecursion('[][]')).toEqual(true)
  expect(bracketsRecursion('[]{}')).toEqual(true)
  expect(bracketsRecursion('[]{}<>')).toEqual(true)
  expect(bracketsRecursion('[]{}<>()')).toEqual(true)
  expect(bracketsRecursion('[[]]')).toEqual(true)
  expect(bracketsRecursion('[[<>]{{()()}}]')).toEqual(true)
  expect(bracketsRecursion('[[[[[][]]]]]')).toEqual(true)
  expect(bracketsRecursion('[[][]]')).toEqual(true)
  expect(bracketsRecursion('[')).toEqual(false)
  expect(bracketsRecursion(']')).toEqual(false)
  expect(bracketsRecursion('[({<')).toEqual(false)
  expect(bracketsRecursion(')}>]')).toEqual(false)
  expect(bracketsRecursion('[[<]>]')).toEqual(false)
})
